site_name: Deployment Pipeline
theme:
  name: material

nav:
  - Home: index.md
  - Functional Documentation:
      - Overview: functional/overview.md
      - Modules: functional/functional-usecases.md
      
  - Use Case Documentation:
      - Business Overview: use-cases/business-overview.md

plugins:
  - search




